sensor:
  - platform: homeassistant
    entity_id: sensor.grange_wind
    id: windnow
  - platform: homeassistant
    entity_id: sensor.openweathermap_temperature
    id: tempnow
  - platform: homeassistant
    entity_id: sensor.sun_next_rising
    id: sunrising
  - platform: homeassistant
    entity_id: sensor.sun_next_setting
    id: sunsetting
  - platform: homeassistant
    entity_id: sensor.grange_thunderstorm_probability_day_0d
    id: stormd0
  - platform: homeassistant
    entity_id: sensor.grange_thunderstorm_probability_day_1d   
    id: stormd1
  - platform: homeassistant
    entity_id: sensor.grange_thunderstorm_probability_day_2d   
    id: stormd2

  - platform: homeassistant
    entity_id: sensor.kitchen_temperature
    id: kitchen_temp
  - platform: homeassistant
    entity_id: sensor.kitchen_humidity
    id: kitchen_hum
    
  - platform: homeassistant
    entity_id: sensor.temp_boiler_temperature
    id: boiler_temp
  - platform: homeassistant
    entity_id: sensor.temp_boiler_humidity
    id: boiler_hum
  - platform: homeassistant
    entity_id: sensor.bedroom_temp_temperature
    id: bedroom_temp
  - platform: homeassistant
    entity_id: sensor.bedroom_temp_humidity
    id: bedroom_hum
  - platform: homeassistant
    entity_id: sensor.temp_attic_temperature
    id: attic_temp
  - platform: homeassistant
    entity_id: sensor.temp_attic_humidity
    id: attic_hum

  - platform: homeassistant
    entity_id: sensor.weather_milano_temperature
    id: temp_milano

  - platform: homeassistant
    entity_id: sensor.weather_armeno_temperature
    id: temp_armeno

  - platform: homeassistant
    entity_id: sensor.weather_mezzema_temperature
    id: temp_mezzema        

text_sensor:
  - platform: homeassistant
    entity_id: weather.grange_2
    id: weathernow

  - platform: homeassistant
    entity_id: weather.grange_2
    attribute: forecast
    id: accuweatherfore
    internal: yes

  - platform: sun
    type: sunrise
    format: "%H:%M"
    id: sunrise_hour
  - platform: sun
    type: sunset
    format: "%H:%M"
    id: sunset_hour

  - platform: homeassistant
    entity_id: weather.weather_milano
    attribute: forecast
    internal: yes    
    id: weather_milano

  - platform: homeassistant
    entity_id: weather.weather_armeno
    attribute: forecast
    internal: yes        
    id: weather_armeno


  - platform: homeassistant
    entity_id: weather.weather_mezzema
    attribute: forecast
    internal: yes        
    id: weather_mezzema


binary_sensor:
  - platform: homeassistant
    entity_id: input_boolean.binario_di_prova
    id: binariodiprova

  - platform: homeassistant
    entity_id: input_boolean.binary_waste_garden
    id: bin_waste_garden
  - platform: homeassistant
    entity_id: input_boolean.binary_waste_food
    id: bin_waste_food
  - platform: homeassistant
    entity_id: input_boolean.binary_waste_grey
    id: bin_waste_grey
  - platform: homeassistant
    entity_id: input_boolean.binary_waste_green
    id: bin_waste_green
  - platform: homeassistant
    entity_id: input_boolean.binary_giardinieri
    id: bin_giardinieri
  - platform: homeassistant
    entity_id: calendar.recycle_food_waste
    id: cal_food
  - platform: homeassistant
    entity_id: calendar.recycle_grey
    id: cal_grey
  - platform: homeassistant
    entity_id: calendar.recycle_green_blue
    id: cal_green
  - platform: homeassistant
    entity_id: calendar.garden_waste
    id: cal_garden
  - platform: homeassistant
    entity_id: calendar.gardeners
    id: cal_gardeneners