font:
  - file: 'fonts/Roboto-Regular.ttf'
    id: font_regular
    size: 28
    #glyphs:
    #  ['&', '@', '!', ',', '.', '"', '%', '’','(', ')', '+', '-', '_', ':', '°', '0',
    #   '1', '2', '3', '4', '5', '6', '7', '8', '9']      

  - file: 'fonts/Roboto-Bold.ttf'
    id: font_bold
    size: 28
    #glyphs:
    #  ['&', '@', '!', ',', '.', '"', '%', '’','(', ')', '+', '-', '_', ':', '°', '0',
    #   '1', '2', '3', '4', '5', '6', '7', '8', '9','C','k','m','h','/']      

  - file: 'fonts/Roboto-Regular.ttf'
    id: font_regular_75
    size: 75
    glyphs:
      ['&', '@', '!', ',', '.', '"', '%', '’','(', ')', '+', '-', '_', ':', '°', '0',
       '1', '2', '3', '4', '5', '6', '7', '8', '9', 'A', 'B', 'C', 'D', 'E',
       'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S',
       'T', 'U', 'V', 'W', 'X', 'Y', 'Z', ' ', 'a', 'b', 'c', 'd', 'e', 'f',
       'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't',
       'u', 'v', 'w', 'x', 'y', 'z','å', 'ä', 'ö', '/','º','µ','³']    
    
  - file: 'fonts/Itim-Regular.ttf'
    id: font_date
    size: 35

  - file: 'fonts/Itim-Regular.ttf'
    id: font_date_big
    size: 45
    glyphs:
      ['0','1', '2', '3', '4', '5', '6', '7', '8', '9']  

  - file: 'fonts/materialdesignicons-webfont.ttf'
    id: icon_font_old
    size: 65
    glyphs: [
      "\U000F156D", # living room
      "\U000F01E6", # gym
      "\U000F181D", # kitchen
      "\U000F0FD1", # mastbed
      "\U000F112B", # attiv
      "\U000F1087", # server
      "\U000F0322", # lg studio
      "\U000F0AAB" # al studio
      ]
  - file: 'fonts/Font Awesome 6 Pro-Light-300.otf'
    id: icon_font
    size: 63
    glyphs: [
      "\uf4b8", # living room
      "\uf44b", # gym
      "\ue51a", # kitchen
      "\uf8f7", # mastbed
      "\uf7d9", # attic
      "\uf233", # server
      "\ue4e5", # lg studio
      "\uf109" # al studio
      ]

  - file: 'fonts/materialdesignicons-webfont.ttf'
    id: weather_font_85_old
    size: 85
    glyphs: [
      # Weather
      "\U000F0590", # cloudy
      "\U000F0594", # clear-night
      "\U000F0591", # fog
      "\U000F0592", # hail
      "\U000F0593", # lightning
      "\U000F067E", # lightning-rainy
      "\U000F0595", # partly-cloudy
      "\U000F0596", # pouring
      "\U000F0597", # rainy
      "\U000F0598", # snowy
      "\U000F067F", # snowy-rainy
      "\U000F0599", # clear-day
      "\U000F059B", # sunset-down
      "\U000F059C", # sunset-up
      "\U000F059D", # windy
      "\U000F059E", # windy-variant
      ]

  - file: 'fonts/Font Awesome 6 Pro-Solid-900.otf'
    id: weather_font_big
    size: 83
    glyphs: [
      # Weather
      "\uf744", # cloudy
      "\uf762", # clear-night
      "\uf74e", # fog
      "\uf739", # hail
      "\uf76c", # lightning
      "\uf76e", # lightning-rainy
      "\uf763", # partly-cloudy
      "\uf740", # pouring
      "\uf73f", # rainy
      "\uf2dc", # snowy
      "\uf73d", # snowy-rainy
      "\uf185", # clear-day
      "\uf767", # sunset-down
      "\uf766", # sunset-up
      "\uf777", # windy
      "\uf6f4", # windy-variant
      ]
  - file: 'fonts/Font Awesome 6 Pro-Light-300.otf'
    id: wind_font
    size: 38
    glyphs: [
      # Weather
      "\uf72e", # windy
      "\uf777" # windy-variant
      ]

  - file: 'fonts/Font Awesome 6 Pro-Light-300.otf'
    id: sun_font
    size: 40
    glyphs: [
      # Weather
      "\uf766", # sun up
      "\uf767" # sun down
      ]

  - file: 'fonts/Font Awesome 6 Pro-Light-300.otf'
    id: icon_font_small
    size: 24
    glyphs: [
      "\uf2ca", # temperature
      "\uf750" # humidity
      ]
  - file: 'fonts/Font Awesome 6 Pro-Solid-900.otf'
    id: icon_font_storm
    size: 30
    glyphs: [
      "\uf76c" # storm
      ]
  - file: 'fonts/Itim-Regular.ttf'
    id: clockfont
    size: 64
    glyphs:
      ['&', '@', '!', ',', '.', '"', '%', '’','(', ')', '+', '-', '_', ':', '°', '0',
       '1', '2', '3', '4', '5', '6', '7', '8', '9']  

  - file: 'fonts/KleeOne-SemiBold.ttf'
    id: jaweekfont
    size: 70
    glyphs:
      ['月','火','水','木','金','土','日']    

  - file: 'fonts/moon_phases.ttf'
    id: moon_font
    size: 95
  - file: 'fonts/moon_phases.ttf'
    id: moon_font_big
    size: 120

