#binary_sensor:
#  - platform: homeassistant
#    entity_id: binary_sensor.contact_sensor_3
#    id: gym_door
#    device_class: door
#  - platform: homeassistant
#    entity_id: binary_sensor.server_door
#    id: server_door
#    device_class: door
#  - platform: homeassistant
#    entity_id: binary_sensor.contact_sensor_2
#    id: main_door
#    device_class: door

sensor:
  # Kitchen
  - platform: homeassistant
    entity_id: sensor.kitchen_temperature
    id: kitchen_temp
  - platform: homeassistant
    entity_id: sensor.kitchen_humidity
    id: kitchen_hum

  # Living Room
  - platform: homeassistant
    entity_id: sensor.living_room_temperature
    id: livingroom_temp
  - platform: homeassistant
    entity_id: sensor.living_room_humidity
    id: livingroom_hum    

  # Master Bedroom
  - platform: homeassistant
    entity_id: sensor.master_bedroom_temperature
    id: mastbed_temp
  - platform: homeassistant
    entity_id: sensor.master_bedroom_humidity
    id: mastbed_hum    

  # Guest Bedroom
  - platform: homeassistant
    entity_id: sensor.guest_bedroom_temperature
    id: guestbed_temp
  - platform: homeassistant
    entity_id: sensor.guest_bedroom_humidity
    id: guestbed_hum  

  # AL Studio
  - platform: homeassistant
    entity_id: sensor.al_studio_temperature
    id: alstudio_temp
  - platform: homeassistant
    entity_id: sensor.al_studio_humidity
    id: alstudio_hum  

  # LG Studio
  - platform: homeassistant
    entity_id: sensor.lg_studio_temperature
    id: lgstudio_temp
  - platform: homeassistant
    entity_id: sensor.lg_studio_humidity
    id: lgstudio_hum  

  # Attic
  - platform: homeassistant
    entity_id: sensor.temp_attic_temperature
    id: attic_temp
  - platform: homeassistant
    entity_id: sensor.temp_attic_humidity
    id: attic_hum

  # Server
  - platform: homeassistant
    entity_id: sensor.temp_server_temperature
    id: server_temp
  - platform: homeassistant
    entity_id: sensor.temp_server_humidity
    id: server_hum

  - platform: homeassistant
    entity_id: sensor.grange_wind
    id: windnow

  - platform: homeassistant
    entity_id: sensor.openweathermap_temperature
    id: tempnow

  - platform: homeassistant
    entity_id: sensor.sun_next_rising
    id: sunrising

  - platform: homeassistant
    entity_id: sensor.sun_next_setting
    id: sunsetting

  - platform: homeassistant
    entity_id: sensor.grange_thunderstorm_probability_day_0d
    #on_value:
    #  then:
    #    - lambda: 'id(data_updated) = true;'
    id: stormd0
  - platform: homeassistant
    entity_id: sensor.grange_thunderstorm_probability_day_1d
    #on_value:
    #  then:
    #    - lambda: 'id(data_updated) = true;'    
    id: stormd1
  - platform: homeassistant
    entity_id: sensor.grange_thunderstorm_probability_day_2d
    #on_value:
    #  then:
    #    - lambda: 'id(data_updated) = true;'    
    id: stormd2
    
    #Forecast
  - platform: homeassistant
    entity_id: sensor.grange_realfeel_temperature_max_1d
    id: foreneomax1
  - platform: homeassistant
    entity_id: sensor.grange_realfeel_temperature_min_1d
    id: foreneomin1
  - platform: homeassistant
    entity_id: sensor.grange_wind_day_1d
    id: foreneowind1

  - platform: homeassistant
    entity_id: sensor.grange_realfeel_temperature_max_2d
    id: foreneomax2
  - platform: homeassistant
    entity_id: sensor.grange_realfeel_temperature_min_2d
    id: foreneomin2
  - platform: homeassistant
    entity_id: sensor.grange_wind_day_2d
    id: foreneowind2

    ####Pirate Weather#####

    #Today
  - platform: homeassistant
    entity_id: sensor.pw_grange_apparent_temperature
    id: pwtodaytemp
  - platform: homeassistant
    entity_id: sensor.pw_grange_wind_speed
    id: pwtodaywind

    #Day1
  - platform: homeassistant
    entity_id: sensor.pw_grange_overnight_low_apparent_temperature_1d
    id: pwday1mintemp
  - platform: homeassistant
    entity_id: sensor.pw_grange_daytime_high_apparent_temperature_1d
    id: pwday1maxtemp    
  - platform: homeassistant
    entity_id: sensor.pw_grange_wind_speed_1d
    id: pwday1wind

    #Day2
  - platform: homeassistant
    entity_id: sensor.pw_grange_overnight_low_apparent_temperature_2d
    id: pwday2mintemp
  - platform: homeassistant
    entity_id: sensor.pw_grange_daytime_high_apparent_temperature_2d
    id: pwday2maxtemp    
  - platform: homeassistant
    entity_id: sensor.pw_grange_wind_speed_2d
    id: pwday2wind
    
    #moon
  - platform: homeassistant
    entity_id: sensor.pw_grange_moon_phase_0d
    id: pwmoond0
  - platform: homeassistant
    entity_id: sensor.pw_grange_moon_phase_1d
    id: pwmoond1
  - platform: homeassistant
    entity_id: sensor.pw_grange_moon_phase_2d
    id: pwmoond2

text_sensor:

  #PW Icons
  - platform: homeassistant
    entity_id: sensor.pw_grange_icon_0d
    id: pwtodayicon  
  - platform: homeassistant
    entity_id: sensor.pw_grange_icon_1d
    id: pwday1icon  
  - platform: homeassistant
    entity_id: sensor.pw_grange_icon_2d
    id: pwday2icon

  - platform: homeassistant
    entity_id: sensor.moon_phase
    id: moonphase


  #- platform: homeassistant
  #  entity_id: weather.grange
  #  id: weathernow

  #- platform: homeassistant
  #  entity_id: weather.grange
  #  attribute: forecast
  #  id: accuweatherfore
  #  internal: yes

  #- platform: homeassistant
  #  entity_id: sensor.accuweather_condition_kyou
  #  id: accucond1
  #- platform: homeassistant
  #  entity_id: sensor.accuweather_condition_ashita
  #  id: accucond2
  #- platform: homeassistant
  #  entity_id: sensor.accuweather_condition_asatte
  #  id: accucond3


  - platform: sun
    type: sunrise
    format: "%H:%M"
    id: sunrise_hour
  - platform: sun
    type: sunset
    format: "%H:%M"
    id: sunset_hour